services:
  sde-ai-tutorial:
    build:
      context: .
      dockerfile: Dockerfile
    image: sde-ai-tutorial
    container_name: sde-ai-tutorial
    ports:
      - "8888:8888"   # Jupyter Lab
      - "4040-4049:4040-4049" # Spark UI
      - '18080:18080' # Spark History Server
      - "3000:3000"
      - "9000:9000"
    volumes:
      - ./notebooks:/home/app/notebooks


